### ISSUE TITLE
Feature Request: Select Alternate Cursor Styles

### ISSUE THREAD

**Issue by heyligerjon** [maxeth/react-type-animation#49]
I was looking for a way to simulate a command line style animation and came across this package that looks great, however the cursor uses the standard vertical line style, it would be a very useful addition to be able to specify either a block or underscore cursor as well. 

Looking at the code it seems like an update to the cursor prop to accept a specified type instead of a boolean would be the way to go, but I'm not too familiar with Typescript.

**Comment by maxeth** [comment]
Hey,

did you take a look at this section? https://react-type-animation.netlify.app/options#custom-cursor-animation

You could maybe do something like this 

```css
.type::after {
  content: '_';
  animation: cursor 1.1s infinite step-start;
}
 
@keyframes cursor {
  50% {
    opacity: 0;
  }
}
```

```tsx
import './yourGlobalCssFile.css';
 
<TypeAnimation
  cursor={false} // omit the default css typing animation class
  className="type"
  sequence={['One', 800, 'One Two']}
/>;
```
